-- ****** Object: Table XXEMS.SYS_USERS Script Date: 7/2/2013 10:35:32 AM ******
CREATE TABLE "SYS_USERS" (
  "USER_ID" NUMBER(15,0) NOT NULL)
  STORAGE ( 
    NEXT 1048576 ) 
/
CREATE UNIQUE INDEX "PK_SYS_USERS"
  ON "SYS_USERS" ( 
    "USER_ID")
/
ALTER TABLE "SYS_USERS" ADD ( 
  CONSTRAINT "PK_SYS_USERS" 
    PRIMARY KEY ( "USER_ID") 
    USING INDEX "PK_SYS_USERS" 
    ENABLE 
    VALIDATE )
/
