-- ****** Object: Table XXEMS.SYS_USER_ROLES Script Date: 7/2/2013 10:35:19 AM ******
CREATE TABLE "SYS_USER_ROLES" (
  "USER_ROLE_ID" NUMBER(15,0) NOT NULL,
  "USER_ID" NUMBER(15,0) NOT NULL,
  "ROLE_ID" NUMBER(15,0) NOT NULL)
  STORAGE ( 
    NEXT 1048576 ) 
/
CREATE UNIQUE INDEX "PK_SYS_USER_ROLES"
  ON "SYS_USER_ROLES" ( 
    "USER_ROLE_ID")
/
ALTER TABLE "SYS_USER_ROLES" ADD ( 
  CONSTRAINT "PK_SYS_USER_ROLES" 
    PRIMARY KEY ( "USER_ROLE_ID") 
    USING INDEX "PK_SYS_USER_ROLES" 
    ENABLE 
    VALIDATE )
/
CREATE TRIGGER XXEMS.TGR_SYS_USER_ROLES
BEFORE INSERT ON XXEMS.SYS_USER_ROLES
FOR EACH ROW
WHEN (
new.USER_ROLE_ID IS NULL
      )
BEGIN
  SELECT XXEMS.SEQ_SYS_USER_ROLES.NEXTVAL
  INTO   :new.USER_ROLE_ID
  FROM   dual;
END;
/
