-- ****** Object: Table XXEMS.SYS_ROLES Script Date: 7/2/2013 10:35:15 AM ******
CREATE TABLE "SYS_ROLES" (
  "ROLE_ID" NUMBER(15,0) NOT NULL,
  "NAME" VARCHAR2(500 BYTE) NOT NULL,
  "DESCRIPTION" VARCHAR2(500 BYTE) NOT NULL)
  STORAGE ( 
    NEXT 1048576 ) 
/
CREATE UNIQUE INDEX "PK_SYS_ROLES"
  ON "SYS_ROLES" ( 
    "ROLE_ID")
/
ALTER TABLE "SYS_ROLES" ADD ( 
  CONSTRAINT "PK_SYS_ROLES" 
    PRIMARY KEY ( "ROLE_ID") 
    USING INDEX "PK_SYS_ROLES" 
    ENABLE 
    VALIDATE )
/
CREATE TRIGGER XXEMS.TGR_SYS_ROLES
BEFORE INSERT ON XXEMS.SYS_ROLES 
FOR EACH ROW
WHEN (
new.ROLE_ID IS NULL
      )
BEGIN
  SELECT XXEMS.SEQ_SYS_ROLES.NEXTVAL
  INTO   :new.ROLE_ID
  FROM   dual;
END;
/
