-- ****** Object: Table XXEMS.SYS_PERMISSIONS Script Date: 7/2/2013 10:34:45 AM ******
CREATE TABLE "SYS_PERMISSIONS" (
  "PERMISSION_ID" NUMBER(15,0) NOT NULL,
  "CODE" VARCHAR2(500 BYTE) NOT NULL,
  "DESCRIPTION" VARCHAR2(500 BYTE) NOT NULL)
  STORAGE ( 
    NEXT 1048576 ) 
/
CREATE UNIQUE INDEX "PK_SYS_PERMISSIONS"
  ON "SYS_PERMISSIONS" ( 
    "PERMISSION_ID")
/
ALTER TABLE "SYS_PERMISSIONS" ADD ( 
  CONSTRAINT "PK_SYS_PERMISSIONS" 
    PRIMARY KEY ( "PERMISSION_ID") 
    USING INDEX "PK_SYS_PERMISSIONS" 
    ENABLE 
    VALIDATE )
/
CREATE TRIGGER XXEMS.TGR_SYS_PERMISSIONS
BEFORE INSERT ON XXEMS.SYS_PERMISSIONS 
FOR EACH ROW
WHEN (
new.PERMISSION_ID IS NULL
      )
BEGIN
  SELECT XXEMS.SEQ_SYS_PERMISSIONS.NEXTVAL
  INTO   :new.PERMISSION_ID
  FROM   dual;
END;
/
