using System;
using System.Collections.Generic;

namespace DBI.Data.Models
{
    /// <summary>
    /// This is the class file generated for the SYS_USERS table, containing a link to the FND_USER table. It will be used to store additional information
    /// Attributes can be added at will to store this additional data.
    /// </summary>
    public partial class SYS_USERS
    {
        /// <summary>
        /// Autogenerated id field.
        /// </summary>
        public long USER_ID { get; set; }
        /// <summary>
        /// FK to the FND_USER table
        /// </summary>
        public string FND_USER_ID { get; set; }

    }
}
