//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CROSSING_RELATIONSHIP
    {
        public decimal RELATIONSHIP_ID { get; set; }
        public Nullable<long> PROJECT_ID { get; set; }
        public Nullable<long> CROSSING_ID { get; set; }
    }
}
