//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPENDITURE_TYPE_V
    {
        public Nullable<long> PROJECT_ID { get; set; }
        public string EXPENDITURE_TYPE { get; set; }
        public Nullable<decimal> BILL_RATE { get; set; }
        public string UNIT_OF_MEASURE { get; set; }
        public string RATE_CURRENCY_CODE { get; set; }
        public System.DateTime LAST_UPDATE_DATE { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
