//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEADS_COMMENTS
    {
        public decimal COMMENT_ID { get; set; }
        public decimal LEAD_ID { get; set; }
        public Nullable<System.DateTime> COMMENT_DATE { get; set; }
        public Nullable<decimal> PERSON_ID { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string MODIFIED_BY { get; set; }
    
        public virtual LEADS_MANAGE_MAIN LEADS_MANAGE_MAIN { get; set; }
    }
}
