//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SURVEY_QUESTIONS
    {
        public SURVEY_QUESTIONS()
        {
            this.SURVEY_FORMS_ANS = new HashSet<SURVEY_FORMS_ANS>();
            this.SURVEY_OPTIONS = new HashSet<SURVEY_OPTIONS>();
            this.SURVEY_RELATION = new HashSet<SURVEY_RELATION>();
        }
    
        public decimal QUESTION_ID { get; set; }
        public decimal TYPE_ID { get; set; }
        public string TEXT { get; set; }
        public string IS_REQUIRED { get; set; }
        public string IS_ACTIVE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public decimal SORT_ORDER { get; set; }
        public decimal CATEGORY_ID { get; set; }
    
        public virtual ICollection<SURVEY_FORMS_ANS> SURVEY_FORMS_ANS { get; set; }
        public virtual ICollection<SURVEY_OPTIONS> SURVEY_OPTIONS { get; set; }
        public virtual SURVEY_QUES_TYPES SURVEY_QUES_TYPES { get; set; }
        public virtual ICollection<SURVEY_RELATION> SURVEY_RELATION { get; set; }
    }
}
