//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBI.Data
{
    using System;
    
    public partial class SYS_USER_ACTIVITY_CT
    {
        public long USER_ACTIVITY_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
