//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_MENU
    {
        public decimal MENU_ID { get; set; }
        public string ITEM_NAME { get; set; }
        public string ITEM_URL { get; set; }
        public decimal MODULE_ID { get; set; }
        public decimal PERMISSION_ID { get; set; }
        public string ICON { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string MODIFIED_BY { get; set; }
    
        public virtual SYS_MODULES SYS_MODULES { get; set; }
        public virtual SYS_PERMISSIONS SYS_PERMISSIONS { get; set; }
    }
}
