//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_ORG_PROFILE_OPTIONS
    {
        public decimal ORG_PROFILE_OPTION_ID { get; set; }
        public long ORGANIZATION_ID { get; set; }
        public decimal PROFILE_OPTION_ID { get; set; }
        public string PROFILE_VALUE { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
    }
}
