//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBI.Data.DataFactory.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBI.Data.DataFactory.Messages.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error deleting your activity..
        /// </summary>
        public static string DeleteActivity {
            get {
                return ResourceManager.GetString("DeleteActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity can not be deleted because it is assigned to an existing user..
        /// </summary>
        public static string DeleteActivityAssignedToUser {
            get {
                return ResourceManager.GetString("DeleteActivityAssignedToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity can not be deleted because it does not exist, please refresh the details window..
        /// </summary>
        public static string DeleteActivityDoesNotExist {
            get {
                return ResourceManager.GetString("DeleteActivityDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error getting activities from the system. .
        /// </summary>
        public static string GetActivities {
            get {
                return ResourceManager.GetString("GetActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error getting your activity..
        /// </summary>
        public static string GetActivity {
            get {
                return ResourceManager.GetString("GetActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error getting your security from the system..
        /// </summary>
        public static string GetClaims {
            get {
                return ResourceManager.GetString("GetClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error getting open activities from the system..
        /// </summary>
        public static string GetOpenActivities {
            get {
                return ResourceManager.GetString("GetOpenActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity can not be saved..
        /// </summary>
        public static string SaveActivity {
            get {
                return ResourceManager.GetString("SaveActivity", resourceCulture);
            }
        }
    }
}
